server:
  port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      transaction-id-prefix: pingpong-
      retries: 1
      acks: all
      batch-size: 8192
      buffer-memory: 1024000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  data:
    mongodb:
      uri: mongodb://root:Mongo_27017@192.168.163.139:27017/pingpong
      database: pingpong
      username: root
      password: Mongo_27017
      host: 192.168.163.139
      port: 27017
logging:
  config: classpath:log4j2.xml
#logging:
#  level:
#    root: DEBUG